#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

echo 'before change directory'
cd $OPENSHIFT_REPO_DIR/diy/servicemix
sed -ig 's/OPENSHIFT_DIY_IP/'$OPENSHIFT_DIY_IP'/g' etc/system.properties
sed -ig 's/OPENSHIFT_DIY_IP/'$OPENSHIFT_DIY_IP'/g' etc/activemq-broker.xml
echo 'running servicemix'
bin/servicemix
